/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iterative.deepening;

import iterative.deepening.IDDFS.Graph;

public class App {
    public static void main(String[] args) {

        Graph graph = new Graph(null);
    }
}
